package com.check.sales.view;

import com.check.sales.App;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

public class SaleWindow extends JFrame {

    public AutocompleteJComboBox itemToPick;
    public JPanel containerPane;
    public JTable saleItems;
    public JTextArea orderSum;
    public JTextPane helpArea;
    public JLabel statusLine;
    public JButton addItemButton;

    public JPanel getContainerPane() {
        return containerPane;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        containerPane = new JPanel();
        containerPane.setLayout(new GridLayoutManager(4, 2, new Insets(0, 0, 0, 0), -1, -1));
        containerPane.add(itemToPick, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(247, 30), null, 0, false));
        saleItems = new JTable();
        containerPane.add(saleItems, new GridConstraints(3, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        orderSum = new JTextArea();
        orderSum.setMargin(new Insets(3, 3, 3, 3));
        orderSum.setText("This is textarea");
        containerPane.add(orderSum, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        helpArea = new JTextPane();
        helpArea.setMargin(new Insets(3, 3, 3, 3));
        helpArea.setText("This is text pane");
        containerPane.add(helpArea, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(247, 50), null, 0, false));
        statusLine = new JLabel();
        statusLine.setText("Status Line");
        containerPane.add(statusLine, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        addItemButton = new JButton();
        addItemButton.setLabel("Add to receipt");
        addItemButton.setText("Add to receipt");
        containerPane.add(addItemButton, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return containerPane;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        itemToPick = new AutocompleteJComboBox(App.items);
    }
}
